# -*- coding: utf-8 -*-
"""mcts_2021150449.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKDe-L71ZXzQB27CwwcafmokRw9S-CHD
"""

import time
import random
import copy
import math

from enum import Enum
from typing import Tuple, Union

from abc import ABC, abstractmethod
import networkx as nx
import numpy as np

import matplotlib.pyplot as plt
from IPython.display import display, HTML, clear_output

class GameResult(Enum):
  """
  Enum to encode different states of the game. A game can be in progress (NOT_FINISHED), lost, won, or draw
  """
  NOT_FINISHED = 0
  NAUGHT_WIN = 1
  CROSS_WIN = 2
  DRAW = 3

BOARD_DIM = 5 # type: int
BOARD_SIZE = BOARD_DIM * BOARD_DIM  # type: int
NUM_WIN = 3

class CellState(Enum):
  EMPTY = 0  # type: int
  NAUGHT = 1  # type: int
  CROSS = 2  # type: int

class GomokuBoard:
    """
    The class to encode a gomoku board, including its current state of pieces.
    Also contains various utility methods.
    """

    WIN_CHECK_DIRS = [[(-1, 0), (1, 0)],
                      [(0, -1), (0, 1)],
                      [(-1, 1), (1, -1)],
                      [(-1, -1), (1, 1)]]

    def hash_value(self) -> int:
        """
        Encode the current state of the game (board positions) as an integer. Will be used for caching evaluations
        :return: A collision free hash value representing the current board state
        """
        res = 0
        for i in range(BOARD_SIZE):
            res *= BOARD_DIM
            res += self.state[i].value

        return res

    @staticmethod
    def other_side(side: CellState) -> CellState:
        """
        Utility method to return the value of the other player than the one passed as input
        :param side: The side we want to know the opposite of
        :return: The opposite side to the one passed as input
        """
        if side == CellState.EMPTY:
            raise ValueError("EMPTY has no 'other side'")

        if side == CellState.CROSS:
            return CellState.NAUGHT

        if side == CellState.NAUGHT:
            return CellState.CROSS

        raise ValueError("{} is not a valid side".format(side))

    def __init__(self):
        """
        Create a new Board. If a state is passed in, we use that otherwise we initialize with an empty board
        :param s: Optional board state to initialise the board with
        """
        self.state = np.ndarray(shape=(BOARD_SIZE,), dtype=CellState)
        self.reset()

    def coord_to_pos(self, coord: Tuple[int, int]) -> int:
        """
        Converts a 2D board position to a 1D board position.
        Various parts of code prefer one over the other.
        :param coord: A board position in 2D coordinates
        :return: The same board position in 1D coordinates
        """
        return coord[0] * BOARD_DIM + coord[1]

    def pos_to_coord(self, pos: int) -> Tuple[int, int]:
        """
        Converts a 1D board position to a 2D board position.
        Various parts of code prefer one over the other.
        :param pos: A board position in 1D coordinates
        :return: The same board position in 2D coordinates
        """
        return pos // BOARD_DIM, pos % BOARD_DIM

    def reset(self):
        """
        Resets the game board. All fields are set to be EMPTY.
        """
        self.state.fill(CellState.EMPTY)
        self.who_won = None

    def num_empty(self) -> int:
        """
        Counts and returns the number of empty fields on the board.
        :return: The number of empty fields on the board
        """
        return np.count_nonzero(self.state == CellState.EMPTY)

    def random_empty_spot(self) -> int:
        """
        Returns a random empty spot on the board in 1D coordinates
        :return: A random empty spot on the board in 1D coordinates
        """
        index = np.random.randint(self.num_empty()) # Count all empty spot and random selection among them
        for i in range(BOARD_SIZE):
            if self.state[i] == CellState.EMPTY:
                if index == 0: # if index is zero, then, it means this spot is selected
                    return i
                else:
                    index = index - 1 # if index is not zero, then, it means we have to move next emtpy spot

    def is_legal(self, pos: int) -> bool:
        """
        Tests whether a board position can be played, i.e. is currently empty
        :param pos: The board position in 1D that is to be checked
        :return: Whether the position can be played
        """
        return (0 <= pos < BOARD_SIZE) and (self.state[pos] == CellState.EMPTY)

    def move(self, position: int, side: CellState) -> Union[np.ndarray, GameResult, bool]:
        """
        Places a piece of side "side" at position "position". The position is to be provided as 1D.
        Throws a ValueError if the position is not EMPTY
        returns the new state of the board, the game result after this move, and whether this move has finished the game

        :param position: The position where we want to put a piece
        :param side: What piece we want to play (NAUGHT, or CROSS)
        :return: The game state after the move, The game result after the move, Whether the move finished the game
        """
        if self.state[position] != CellState.EMPTY:
            print('Illegal move')
            raise ValueError("Invalid move")

        self.state[position] = side

        if self.check_win(position, side):
            self.who_won = side
            return self.state, GameResult.CROSS_WIN if side == CellState.CROSS else GameResult.NAUGHT_WIN, True

        if self.num_empty() == 0:
            self.who_won = CellState.EMPTY
            return self.state, GameResult.DRAW, True

        return self.state, GameResult.NOT_FINISHED, False

    def check_win(self, pos: int, side: CellState):
        row = pos // BOARD_DIM
        col = pos % BOARD_DIM

        def check_direction(_dr, _dc):
            count = 0
            r, c = row + _dr, col + _dc
            p = r * BOARD_DIM + c
            while 0 <= r < BOARD_DIM and 0 <= c < BOARD_DIM and self.state[p] == side:
                count += 1
                r += _dr
                c += _dc
                p = r * BOARD_DIM + c
            return count

        directions = [(1, 0), (0, 1), (1, 1), (1, -1)]

        for dr, dc in directions:
            total_count = 1  # Count the current stone
            total_count += check_direction(-dr, -dc)  # Count stones in the opposite direction
            total_count += check_direction(dr, dc)    # Count stones in the original direction

            if total_count >= NUM_WIN:
                return True

        return False

    def state_to_char(self, pos):
        """
        Return 'x', 'o', or ' ' depending on what piece is on 1D position pos. Ig `html` is True,
        return '&ensp' instead of ' ' to enforce a white space in the case of HTML output
        :param pos: The position in 1D for which we want a character representation
        :param html: Flag indicating whether we want an ASCII (False) or HTML (True) character
        :return: 'x', 'o', or ' ' depending on what piece is on 1D position pos. Ig `html` is True,
        return '&ensp' instead of ' '
        """
        if (self.state[pos]) == CellState.NAUGHT:
            return 'O'
        elif (self.state[pos]) == CellState.CROSS:
            return 'X'

def draw_go_board(board: GomokuBoard):
    clear_output(wait=True)
    fig, ax = plt.subplots(figsize=(BOARD_DIM, BOARD_DIM))
    ax.set_xlim(0, BOARD_DIM)
    ax.set_ylim(0, BOARD_DIM)

    cell_size = 0.97
    rect_offset = (1.-cell_size) / 2  # Offset to center the cells
    offset = 1 / 2

    # Draw black board
    ax.add_patch(plt.Rectangle((0, 0), BOARD_DIM, BOARD_DIM, color='black', fill=True))

    # Draw white cells
    for x in range(BOARD_DIM):
        for y in range(BOARD_DIM):
            ax.add_patch(plt.Rectangle((x + rect_offset, y + rect_offset), cell_size, cell_size, color='white', fill=True))

    # Place markers
    for x in range(BOARD_DIM):
        for y in range(BOARD_DIM):
            pos = x * BOARD_DIM + y
            marker = board.state_to_char(pos)
            ax.text(x + offset, y + offset, marker, ha='center', va='center', fontsize=20)

    ax.set_xticks([])
    ax.set_yticks([])
    ax.set_aspect('equal')
    plt.show()
    time.sleep(0.5)

board = GomokuBoard()
draw_go_board(board)

class GamePlayerInterface(ABC):
    """
    Interface for Gomoku player
    """
    def __init__(self):
        super().__init__()

    @abstractmethod
    def move(self, board: GomokuBoard) -> Union[GameResult, bool]:
        pass

    @abstractmethod
    def new_game(self, side: CellState):
        pass

class RandomPlayer(GamePlayerInterface):
    def __init__(self):
        # Initialize the player's side to None
        self.side = None
        super().__init__()

    def move(self, GomokuBoard: GomokuBoard) -> Union[GameResult, bool]:
        # Get a random empty spot on the game board
        location = GomokuBoard.random_empty_spot()

        # Make a move on the game board and capture the result and whether the game is finished
        _, res, finished = GomokuBoard.move(int(location), self.side)

        # Return the move's result and whether the game is finished
        return res, finished

    def new_game(self, side: CellState):
        # Set the player's side at the start of a new game
        self.side = side

def play_game(board: GomokuBoard, player1: GamePlayerInterface, player2: GamePlayerInterface, drawing_board: bool = True):
    player1.new_game(CellState.CROSS)
    player2.new_game(CellState.NAUGHT)
    board.reset()

    finished = False
    while not finished:
        result, finished = player1.move(board)
        if drawing_board:
            draw_go_board(board)
        if finished:
            continue
        else:
            result, finished = player2.move(board)
            if drawing_board:
                draw_go_board(board)
    return result

def battle(player1: GamePlayerInterface, player2: GamePlayerInterface, num_games: int = 1000, silent: bool = False):
    board = GomokuBoard()
    draw_count = 0
    cross_count = 0
    naught_count = 0
    for _ in range(num_games):
        result = play_game(board, player1, player2,drawing_board=False)
        if result == GameResult.CROSS_WIN:
            cross_count += 1
        elif result == GameResult.NAUGHT_WIN:
            naught_count += 1
        else:
            draw_count += 1

    if not silent:
        print("After {} game we have draws: {}, GamePlayerInterface 1 wins: {}, and GamePlayerInterface 2 wins: {}.".format(num_games, draw_count,
                                                                                                  cross_count,
                                                                                                  naught_count))

        print("Which gives percentages of draws: {:.2%}, GamePlayerInterface 1 wins: {:.2%}, and GamePlayerInterface 2 wins:  {:.2%}".format(
            draw_count / num_games, cross_count / num_games, naught_count / num_games))

    return cross_count, naught_count, draw_count

class MCTSAlgorithm(GamePlayerInterface):

    WIN_VALUE  = 1
    DRAW_VALUE = 0
    LOSS_VALUE = -1
    ITERATIONS = 200

    def __init__(self):
        self.side: CellState | None = None
        self.tree: nx.DiGraph       = nx.DiGraph()
        super().__init__()

    def new_game(self, side: CellState):
        self.side = side
        self.tree.clear()

    def _candidate_moves(self, board):
        if board.num_empty() == BOARD_SIZE:
            return [BOARD_SIZE // 2]
        neigh = set()
        for idx in range(BOARD_SIZE):
            if board.state[idx] != CellState.EMPTY:
                r, c = divmod(idx, BOARD_DIM)
                for dr in (-1,0,1):
                    for dc in (-1,0,1):
                        nr, nc = r + dr, c + dc
                        if 0<=nr<BOARD_DIM and 0<=nc<BOARD_DIM:
                            pos = nr*BOARD_DIM + nc
                            if board.state[pos] == CellState.EMPTY:
                                neigh.add(pos)
        return list(neigh) if neigh else [i for i in range(BOARD_SIZE)
                                          if board.is_legal(i)]

    def _urgent_move(self, board, side):
        opp = GomokuBoard.other_side(side)
        for pos in self._candidate_moves(board):
            tmp = copy.deepcopy(board); tmp.move(pos, side)
            if tmp.check_win(pos, side):
                return pos
        for pos in self._candidate_moves(board):
            tmp = copy.deepcopy(board); tmp.move(pos, opp)
            if tmp.check_win(pos, opp):
                return pos
        return None

    def simulate_game(self, board: GomokuBoard, first_side: CellState) -> int:
        p1, p2 = RandomPlayer(), RandomPlayer()
        p1.new_game(first_side)
        p2.new_game(GomokuBoard.other_side(first_side))

        b, side, done = copy.deepcopy(board), first_side, False
        while not done:
            mv = self._urgent_move(b, side) or random.choice(self._candidate_moves(b))
            _, res, done = b.move(mv, side)
            side = GomokuBoard.other_side(side)

        if res == GameResult.DRAW:
            return self.DRAW_VALUE
        win = ((res == GameResult.CROSS_WIN and self.side == CellState.CROSS) or
               (res == GameResult.NAUGHT_WIN and self.side == CellState.NAUGHT))
        return self.WIN_VALUE if win else self.LOSS_VALUE

    def _ensure_node(self, board, mover):
        nid = board.hash_value()
        if nid not in self.tree:
            self.tree.add_node(nid, N=0, W=0.0)
        if self.tree.out_degree(nid) == 0 and board.who_won is None:
            for pos in self._candidate_moves(board):
                child = copy.deepcopy(board); child.move(pos, mover)
                cid = child.hash_value()
                if cid not in self.tree:
                    self.tree.add_node(cid, N=0, W=0.0)
                self.tree.add_edge(nid, cid, action=pos)
        return nid

    def _ucb_child(self, nid, maximise):
        best, choice = float('-inf'), None
        parent_N = self.tree.nodes[nid]['N']
        for cid in self.tree.successors(nid):
            N_c = self.tree.nodes[cid]['N']
            if N_c == 0:
                return cid
            exploit = self.tree.nodes[cid]['W'] / N_c
            if not maximise:
                exploit = -exploit
            explore = math.sqrt(2) * math.sqrt(math.log(parent_N) / N_c) if parent_N else float('inf')
            val = exploit + explore
            if val > best:
                best, choice = val, cid
        return choice

    def _max(self, board):
        if board.who_won is not None:
            return (self.WIN_VALUE if board.who_won == self.side else
                    self.LOSS_VALUE) if board.who_won != CellState.EMPTY else \
                   (self.DRAW_VALUE), -1

        nid = self._ensure_node(board, self.side)
        cid = self._ucb_child(nid, True)
        mv  = self.tree.edges[nid, cid]['action']

        if self.tree.nodes[cid]['N'] == 0:
            child_board = copy.deepcopy(board); child_board.move(mv, self.side)
            val = self.simulate_game(child_board, GomokuBoard.other_side(self.side))
            self.tree.nodes[cid]['N'] = 1
            self.tree.nodes[cid]['W'] = val
        else:
            next_b = copy.deepcopy(board); next_b.move(mv, self.side)
            val, _ = self._min(next_b)

        self.tree.nodes[nid]['N'] += 1
        self.tree.nodes[nid]['W'] += val
        return val, mv

    def _min(self, board):
        if board.who_won is not None:
            return (self.WIN_VALUE if board.who_won == self.side else
                    self.LOSS_VALUE) if board.who_won != CellState.EMPTY else \
                   (self.DRAW_VALUE), -1

        opp = GomokuBoard.other_side(self.side)
        nid = self._ensure_node(board, opp)
        cid = self._ucb_child(nid, False)
        mv  = self.tree.edges[nid, cid]['action']

        if self.tree.nodes[cid]['N'] == 0:
            child_board = copy.deepcopy(board); child_board.move(mv, opp)
            val = self.simulate_game(child_board, self.side)
            self.tree.nodes[cid]['N'] = 1
            self.tree.nodes[cid]['W'] = val
        else:
            next_b = copy.deepcopy(board); next_b.move(mv, opp)
            val, _ = self._max(next_b)

        self.tree.nodes[nid]['N'] += 1
        self.tree.nodes[nid]['W'] += val
        return val, mv

    def find_optimal_move(self, current_node, find_max):
        best_score = float('-inf') if find_max else float('inf')
        best = []
        for cid in self.tree.successors(current_node):
            N = self.tree.nodes[cid]['N']
            avg = 0.0 if N == 0 else self.tree.nodes[cid]['W'] / N
            if (find_max and avg > best_score) or (not find_max and avg < best_score):
                best_score, best = avg, [cid]
            elif avg == best_score:
                best.append(cid)
        if not best:
            return best_score, -1
        chosen = random.choice(best)
        mv = self.tree.edges[current_node, chosen]['action']
        return best_score, mv

    def move(self, board):
        urgent = self._urgent_move(board, self.side)
        if urgent is not None:
            _, res, fin = board.move(urgent, self.side)
            return res, fin

        for _ in range(self.ITERATIONS):
            self._max(copy.deepcopy(board))

        root_id = self._ensure_node(board, self.side)
        _, best_mv = self.find_optimal_move(root_id, True)
        if best_mv == -1:
            best_mv = random.choice(self._candidate_moves(board))

        _, res, fin = board.move(best_mv, self.side)
        return res, fin

player1 = MCTSAlgorithm()
player2 = RandomPlayer()
cross_count, naught_count, draw_count = battle(player1, player2, num_games=100)

player1 = RandomPlayer()
player2 = MCTSAlgorithm()
cross_count, naught_count, draw_count = battle(player1, player2, num_games=100)